name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Create wrangler.toml
        run: |
          cat > wrangler.toml << EOF
          name = "birthday-reminder"
          main = "src/index.ts"
          compatibility_date = "2024-01-01"

          routes = [
            { pattern = "${{ secrets.DOMAIN }}", custom_domain = true }
          ]

          [triggers]
          crons = ["0 9 * * *"]

          [vars]
          TELEGRAM_BOT_TOKEN = "${{ secrets.TELEGRAM_BOT_TOKEN }}"
          TELEGRAM_CHAT_ID = "${{ secrets.TELEGRAM_CHAT_ID }}"

          [[kv_namespaces]]
          binding = "BIRTHDAYS"
          id = "${{ secrets.KV_NAMESPACE_ID }}"
          EOF

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}